export interface CountryItem {
  id?: number;
  name: string;
  slug: string;
  code: string;
  region: string;
  regionLabel: string;
  description: string;
  image: string;
  latitude: number;
  longitude: number;
  highlights?: string[];
  featured?: boolean;
}

export interface RegionGroup {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  coverImage: string;
  iconName: string;
  countries: CountryItem[];
}

export const COUNTRIES_DATA: CountryItem[] = [
  // ── East Asia / Far East ──
  {
    name: "Japan",
    slug: "japan",
    code: "JP",
    region: "east-asia",
    regionLabel: "East Asia & Far East",
    description: "Centuries of serene temple rituals, neon-lit bullet trains, hot-spring ryokans, and sublime culinary artistry.",
    image: "/images/dest-japan.jpg",
    latitude: 36.2048,
    longitude: 138.2529,
    highlights: ["Kyoto Bamboo Groves & Shrines", "Mount Fuji & Hakone Ryokans", "Tokyo Ginza & Omotesando"],
    featured: true,
  },
  {
    name: "South Korea",
    slug: "south-korea",
    code: "KR",
    region: "east-asia",
    regionLabel: "East Asia & Far East",
    description: "Royal Joseon palaces, tranquil hanok heritage villages, volcanic Jeju island, and world-leading contemporary arts.",
    image: "/images/world/countries/south-korea.jpg",
    latitude: 35.9078,
    longitude: 127.7669,
    highlights: ["Gyeongbokgung Palace", "Jeju Lava Tubes & Coast", "Bukchon Hanok Village"],
    featured: false,
  },
  {
    name: "China",
    slug: "china",
    code: "CN",
    region: "east-asia",
    regionLabel: "East Asia & Far East",
    description: "A land of breathtaking epic scale: ancient Great Wall fortifications, imperial pavilions, and karst mountain riverways.",
    image: "/images/world/countries/china.jpg",
    latitude: 35.8617,
    longitude: 104.1954,
    highlights: ["Great Wall of China", "Forbidden City Beijing", "Guilin Karst Mountains"],
    featured: false,
  },

  // ── Southeast Asia ──
  {
    name: "Thailand",
    slug: "thailand",
    code: "TH",
    region: "southeast-asia",
    regionLabel: "Southeast Asia",
    description: "Gilded royal temples, emerald limestone sea pillars rising from Andaman waters, and world-renowned hospitality.",
    image: "/images/world/attractions/grand-palace-wat-phra-kaew.jpg",
    latitude: 15.87,
    longitude: 100.9925,
    highlights: ["Grand Palace Bangkok", "Phang Nga & Railay Limestone Bays", "Chiang Mai Mountain Retreats"],
    featured: true,
  },
  {
    name: "Vietnam",
    slug: "vietnam",
    code: "VN",
    region: "southeast-asia",
    regionLabel: "Southeast Asia",
    description: "Atmospheric lantern-lit heritage alleys in Hoi An, majestic dragon-spine seascapes in Halong Bay, and vibrant markets.",
    image: "/images/world/attractions/phang-nga-bay.jpg",
    latitude: 14.0583,
    longitude: 108.2772,
    highlights: ["Halong Bay Cruises", "Hoi An Ancient Town", "Mekong River Sanctuaries"],
    featured: true,
  },
  {
    name: "Indonesia",
    slug: "indonesia",
    code: "ID",
    region: "southeast-asia",
    regionLabel: "Southeast Asia",
    description: "Sacred volcanic peaks, tiered jungle rice terraces, pristine coral atolls, and spiritual retreats across the archipelago.",
    image: "/images/world/attractions/batu-caves.jpg",
    latitude: -0.7893,
    longitude: 113.9213,
    highlights: ["Ubud Sacred Terraces", "Komodo Island National Park", "Borobudur Temple"],
    featured: false,
  },
  {
    name: "Malaysia",
    slug: "malaysia",
    code: "MY",
    region: "southeast-asia",
    regionLabel: "Southeast Asia",
    description: "Glittering capital horizons, misty tea-carpeted Cameron Highlands, and ancient rainforest islands.",
    image: "/images/world/attractions/petronas-twin-towers.jpg",
    latitude: 4.2105,
    longitude: 101.9758,
    highlights: ["Petronas Towers", "Langkawi Geoforest Reserve", "Penang Heritage Mansions"],
    featured: false,
  },
  {
    name: "Singapore",
    slug: "singapore",
    code: "SG",
    region: "southeast-asia",
    regionLabel: "Southeast Asia",
    description: "An oasis garden metropolis pairing visionary architectural icons, Michelin-starred gastronomy, and luxury waterfronts.",
    image: "/images/world/regions/southeast-asia.jpg",
    latitude: 1.3521,
    longitude: 103.8198,
    highlights: ["Gardens by the Bay", "Marina Bay Waterfront", "Changi Canopy Park"],
    featured: false,
  },

  // ── Western & Southern Europe ──
  {
    name: "France",
    slug: "france",
    code: "FR",
    region: "western-europe",
    regionLabel: "Western Europe",
    description: "Palaces of Versailles, world-famous Parisian art museums, rolling Champagne vineyards, and sun-kissed Riviera coves.",
    image: "/images/world/attractions/eiffel-tower.jpg",
    latitude: 46.2276,
    longitude: 2.2137,
    highlights: ["Eiffel Tower & Louvre Museum", "French Riviera & Côte d'Azur", "Mont-Saint-Michel"],
    featured: true,
  },
  {
    name: "Italy",
    slug: "italy",
    code: "IT",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "Renaissance Florence, romantic Venetian canals, imperial Roman monuments, and dramatic cliffside Amalfi vistas.",
    image: "/images/world/attractions/venice-grand-canal-st-marks.jpg",
    latitude: 41.8719,
    longitude: 12.5674,
    highlights: ["Venice Grand Canal", "Rome Colosseum & Vatican", "Florence Uffizi Gallery"],
    featured: true,
  },
  {
    name: "Spain",
    slug: "spain",
    code: "ES",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "Moorish palace architecture in Andalusia, Gaudí's fantastical creations in Barcelona, and world-class culinary excellence.",
    image: "/images/world/attractions/real-alcazar-seville.jpg",
    latitude: 40.4637,
    longitude: -3.7492,
    highlights: ["Alhambra & Seville Alcázar", "Sagrada Família Barcelona", "Madrid Prado Museum"],
    featured: false,
  },
  {
    name: "Switzerland",
    slug: "switzerland",
    code: "CH",
    region: "alps-central-europe",
    regionLabel: "Alps & Central Europe",
    description: "Soaring alpine summits, glacier railways, crystal-clear mountain lakes, and immaculate storybook chalets.",
    image: "/images/world/attractions/glacier-express.jpg",
    latitude: 46.8182,
    longitude: 8.2275,
    highlights: ["Matterhorn & Gornergrat", "Glacier Express Panoramic Train", "Jungfraujoch Top of Europe"],
    featured: true,
  },
  {
    name: "Greece",
    slug: "greece",
    code: "GR",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "Classical Acropolis marble temples, whitewashed Cycladic island villages, and cobalt Aegean waters.",
    image: "/images/world/attractions/oia-santorini.jpg",
    latitude: 39.0742,
    longitude: 21.8243,
    highlights: ["Oia Santorini Sunset Views", "Acropolis of Athens", "Meteora Monasteries"],
    featured: false,
  },
  {
    name: "United Kingdom",
    slug: "united-kingdom",
    code: "GB",
    region: "western-europe",
    regionLabel: "Western Europe",
    description: "Royal palaces, majestic Scottish highlands and lochs, historic castle strongholds, and world-renowned theaters.",
    image: "/images/world/attractions/edinburgh-castle-royal-mile.jpg",
    latitude: 55.3781,
    longitude: -3.436,
    highlights: ["Edinburgh Castle & Royal Mile", "Tower of London", "Isle of Skye & Highlands"],
    featured: false,
  },
  {
    name: "Turkey",
    slug: "turkey",
    code: "TR",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "The meeting point of East and West: Istanbul's minarets, surreal hot-air balloon skies over Cappadocia, and turquoise bays.",
    image: "/images/world/countries/turkey.jpg",
    latitude: 38.9637,
    longitude: 35.2433,
    highlights: ["Cappadocia Hot Air Ballooning", "Hagia Sophia Istanbul", "Pamukkale Thermal Terraces"],
    featured: true,
  },
  {
    name: "Austria",
    slug: "austria",
    code: "AT",
    region: "alps-central-europe",
    regionLabel: "Alps & Central Europe",
    description: "Habsburg imperial palaces, classical Vienna opera, baroque Salzburg, and pristine Alpine lake country.",
    image: "/images/world/regions/alps-central-europe.jpg",
    latitude: 47.5162,
    longitude: 14.5501,
    highlights: ["Schönbrunn Palace Vienna", "Salzburg Old Town", "Hallstatt Lake Sanctuary"],
    featured: false,
  },
  {
    name: "Portugal",
    slug: "portugal",
    code: "PT",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "Sun-drenched Atlantic coastlines, terraced Douro river vineyards, and historic azulejo-tiled quarters in Lisbon.",
    image: "/images/world/attractions/prado-museum.jpg",
    latitude: 39.3999,
    longitude: -8.2245,
    highlights: ["Lisbon Alfama & Belém", "Douro Valley Wine Estates", "Algarve Golden Sea Caves"],
    featured: false,
  },
  {
    name: "Croatia",
    slug: "croatia",
    code: "HR",
    region: "mediterranean",
    regionLabel: "Southern Europe & Mediterranean",
    description: "Medieval walled citadels, emerald waterfall national parks, and sailing along thousands of Adriatic islands.",
    image: "/images/world/attractions/mykonos-little-venice.jpg",
    latitude: 45.1,
    longitude: 15.2,
    highlights: ["Dubrovnik Medieval Walls", "Plitvice Lakes Waterfalls", "Diocletian's Palace Split"],
    featured: false,
  },

  // ── North Africa ──
  {
    name: "Morocco",
    slug: "morocco",
    code: "MA",
    region: "north-africa",
    regionLabel: "North Africa",
    description: "Labyrinthine imperial medinas, fragrant spice souks, majestic High Atlas passes, and golden Sahara desert dunes.",
    image: "/images/dest-morocco.jpg",
    latitude: 31.7917,
    longitude: -7.0926,
    highlights: ["Marrakech Medina & Riads", "Sahara Desert Luxury Camps", "Chefchaouen Blue City"],
    featured: true,
  },
  {
    name: "Egypt",
    slug: "egypt",
    code: "EG",
    region: "north-africa",
    regionLabel: "North Africa",
    description: "Five millennia of legendary civilization: the Great Pyramids of Giza, Karnak, and private luxury Nile cruises.",
    image: "/images/tour-sahara.jpg",
    latitude: 26.8206,
    longitude: 30.8025,
    highlights: ["Pyramids of Giza & Sphinx", "Valley of the Kings Luxor", "Nile Dahabiya Sailing"],
    featured: true,
  },
  {
    name: "Tunisia",
    slug: "tunisia",
    code: "TN",
    region: "north-africa",
    regionLabel: "North Africa",
    description: "Ancient Carthage ruins, golden Roman amphitheaters, whitewashed Mediterranean cliffside villages, and desert oases.",
    image: "/images/hero-sahara.jpg",
    latitude: 33.8869,
    longitude: 9.5375,
    highlights: ["Carthage & Sidi Bou Said", "El Jem Roman Amphitheatre", "Tozeur Saharan Oasis"],
    featured: false,
  },

  // ── Central & Southern Africa / East Africa ──
  {
    name: "South Africa",
    slug: "south-africa",
    code: "ZA",
    region: "central-southern-africa",
    regionLabel: "Central & Southern Africa",
    description: "The dramatic drama of Table Mountain, renowned Cape winelands, and premier private game reserves in Greater Kruger.",
    image: "/images/world/countries/south-africa.jpg",
    latitude: -30.5595,
    longitude: 22.9375,
    highlights: ["Kruger Private Game Lodges", "Cape Town & Table Mountain", "Franschhoek & Stellenbosch Winelands"],
    featured: true,
  },
  {
    name: "Kenya",
    slug: "kenya",
    code: "KE",
    region: "central-southern-africa",
    regionLabel: "Central & Southern Africa",
    description: "The birthplace of the safari: the legendary Great Migration across the Masai Mara, Mount Kenya, and luxury conservation camps.",
    image: "/images/world/countries/kenya.jpg",
    latitude: -0.0236,
    longitude: 37.9062,
    highlights: ["Masai Mara Great Migration", "Amboseli Kilimanjaro Views", "Laikipia Rhino Conservancies"],
    featured: true,
  },
  {
    name: "Tanzania",
    slug: "tanzania",
    code: "TZ",
    region: "central-southern-africa",
    regionLabel: "Central & Southern Africa",
    description: "Endless Serengeti plains, the ancient caldera of Ngorongoro, the snows of Kilimanjaro, and spice-scented Zanzibar.",
    image: "/images/world/countries/tanzania.jpg",
    latitude: -6.369,
    longitude: 34.8888,
    highlights: ["Serengeti Safari Game Drives", "Ngorongoro Crater", "Zanzibar Spice Coast & Stone Town"],
    featured: true,
  },
  {
    name: "Zimbabwe",
    slug: "zimbabwe",
    code: "ZW",
    region: "central-southern-africa",
    regionLabel: "Central & Southern Africa",
    description: "The roaring majesty of Victoria Falls, pristine wildlife sanctuaries in Hwange, and peerless walking safari guides.",
    image: "/images/world/countries/zimbabwe.jpg",
    latitude: -19.0154,
    longitude: 29.1549,
    highlights: ["Victoria Falls Wonder", "Hwange Elephant Herds", "Mana Pools Zambezi Canoe Safaris"],
    featured: false,
  },

  // ── Gulf & Arabia ──
  {
    name: "United Arab Emirates",
    slug: "united-arab-emirates",
    code: "AE",
    region: "gulf-middle-east",
    regionLabel: "Gulf & Arabia",
    description: "Futuristic luxury towers, desert retreats beneath star-filled skies, and world-class cultural institutions like Louvre Abu Dhabi.",
    image: "/images/world/countries/united-arab-emirates.jpg",
    latitude: 23.4241,
    longitude: 53.8478,
    highlights: ["Louvre Abu Dhabi", "Sheikh Zayed Grand Mosque", "Dubai Desert Conservation"],
    featured: false,
  },
  {
    name: "Saudi Arabia",
    slug: "saudi-arabia",
    code: "SA",
    region: "gulf-middle-east",
    regionLabel: "Gulf & Arabia",
    description: "Ancient sandstone tombs in Hegra at AlUla, mud-brick historical wonders, and pristine untouched Red Sea reefs.",
    image: "/images/world/attractions/hegra.jpg",
    latitude: 23.8859,
    longitude: 45.0792,
    highlights: ["Hegra Nabataean Tombs AlUla", "Elephant Rock AlUla", "At-Turaif UNESCO Diriyah"],
    featured: false,
  },

  // ── Indian Ocean ──
  {
    name: "Maldives",
    slug: "maldives",
    code: "MV",
    region: "indian-ocean",
    regionLabel: "Indian Ocean",
    description: "Secluded private island resorts with overwater villas, luminous turquoise lagoons, and abundant manta ray marine life.",
    image: "/images/hero-maldives.jpg",
    latitude: 3.2028,
    longitude: 73.2207,
    highlights: ["Private Overwater Bungalows", "Manta Ray & Whale Shark Diving", "Seaplane Lagoon Flights"],
    featured: true,
  },
  {
    name: "Sri Lanka",
    slug: "sri-lanka",
    code: "LK",
    region: "indian-ocean",
    regionLabel: "Indian Ocean",
    description: "Ancient Sigiriya rock fortresses, sacred Buddhist stupas, emerald Ceylon tea plantations, and golden palm-lined beaches.",
    image: "/images/world/attractions/cameron-highlands-tea.jpg",
    latitude: 7.8731,
    longitude: 80.7718,
    highlights: ["Sigiriya Lion Rock Fortress", "Tea Plantations in Nuwara Eliya", "Galle Dutch Fort"],
    featured: false,
  },

  // ── Caucasus & Silk Road ──
  {
    name: "Georgia",
    slug: "georgia",
    code: "GE",
    region: "caucasus-central-asia",
    regionLabel: "Caucasus & Silk Road",
    description: "Snow-capped Caucasus summits, cliffside monasteries, and thousands of years of traditional qvevri winemaking culture.",
    image: "/images/world/countries/georgia.jpg",
    latitude: 42.3154,
    longitude: 43.3569,
    highlights: ["Kazbegi & Gergeti Trinity Church", "Old Town Tbilisi", "Kakheti Wine Valley"],
    featured: false,
  },
  {
    name: "Uzbekistan",
    slug: "uzbekistan",
    code: "UZ",
    region: "caucasus-central-asia",
    regionLabel: "Caucasus & Silk Road",
    description: "Legendary Silk Road crossroads adorned with turquoise mosaic domes, soaring minarets, and bustling historic bazaars.",
    image: "/images/world/regions/caucasus-central-asia.jpg",
    latitude: 41.3775,
    longitude: 64.5853,
    highlights: ["Samarkand Registan Square", "Bukhara Historic Fortress", "Khiva Walled Oasis"],
    featured: false,
  },
];

export const REGIONS_DATA: RegionGroup[] = [
  {
    id: "east-asia",
    slug: "east-asia",
    name: "East Asia & Far East",
    tagline: "Imperial Dynasties & Modern Marvels",
    description: "From serene Zen temple gardens and sacred snow peaks to futuristic high-speed metropolises.",
    coverImage: "/images/dest-japan.jpg",
    iconName: "Landmark",
    countries: COUNTRIES_DATA.filter((c) => c.region === "east-asia"),
  },
  {
    id: "southeast-asia",
    slug: "southeast-asia",
    name: "Southeast Asia",
    tagline: "Limestone Bays & Gilded Sanctuaries",
    description: "Warm emerald seas, private tropical islands, and warmhearted hospitality across lush archipelagos.",
    coverImage: "/images/world/attractions/grand-palace-wat-phra-kaew.jpg",
    iconName: "Waves",
    countries: COUNTRIES_DATA.filter((c) => c.region === "southeast-asia"),
  },
  {
    id: "western-europe",
    slug: "western-europe",
    name: "Western & Southern Europe",
    tagline: "Grand Capitals, Riviera Coastlines & Historic Splendour",
    description: "Centuries of royal heritage, Renaissance masterworks, fine vineyards, and storybook alpine vistas.",
    coverImage: "/images/world/attractions/eiffel-tower.jpg",
    iconName: "Landmark",
    countries: COUNTRIES_DATA.filter(
      (c) => c.region === "western-europe" || c.region === "mediterranean" || c.region === "alps-central-europe"
    ),
  },
  {
    id: "north-africa",
    slug: "north-africa",
    name: "North Africa",
    tagline: "Ancient Pyramids, Medinas & Sahara Dunes",
    description: "Monumental Nile civilisations, labyrinthine imperial spice markets, and serene luxury desert camps.",
    coverImage: "/images/dest-morocco.jpg",
    iconName: "Sun",
    countries: COUNTRIES_DATA.filter((c) => c.region === "north-africa"),
  },
  {
    id: "central-southern-africa",
    slug: "central-southern-africa",
    name: "Central & Southern Africa",
    tagline: "The Great Migration, Victoria Falls & Pristine Safaris",
    description: "Vast savannas teeming with wildlife, thundering cataracts, and ultra-exclusive private game reserves.",
    coverImage: "/images/cat-safari.jpg",
    iconName: "Mountain",
    countries: COUNTRIES_DATA.filter((c) => c.region === "central-southern-africa"),
  },
  {
    id: "gulf-middle-east",
    slug: "gulf-middle-east",
    name: "Gulf & Arabia",
    tagline: "Sandstone Kingdoms & Waterfront Glamour",
    description: "Ancient Nabataean tombs at AlUla, grand mosques, and ultra-modern hospitality by the sea.",
    coverImage: "/images/world/countries/united-arab-emirates.jpg",
    iconName: "Sun",
    countries: COUNTRIES_DATA.filter((c) => c.region === "gulf-middle-east"),
  },
  {
    id: "indian-ocean",
    slug: "indian-ocean",
    name: "Indian Ocean",
    tagline: "Barefoot Atoll Luxury & Emerald Highlands",
    description: "Overwater coral bungalows, manta ray sanctuaries, and misty Ceylon tea hill country.",
    coverImage: "/images/hero-maldives.jpg",
    iconName: "Waves",
    countries: COUNTRIES_DATA.filter((c) => c.region === "indian-ocean"),
  },
  {
    id: "caucasus-central-asia",
    slug: "caucasus-central-asia",
    name: "Caucasus & Silk Road",
    tagline: "Mountain Monasteries & Turquoise Domes",
    description: "Timeless Silk Road oasis cities, legendary hospitality, and Greater Caucasus mountain frontiers.",
    coverImage: "/images/world/attractions/meteora-monasteries.jpg",
    iconName: "Mountain",
    countries: COUNTRIES_DATA.filter((c) => c.region === "caucasus-central-asia"),
  },
];

export function getFeaturedCountries(): CountryItem[] {
  return COUNTRIES_DATA.filter((c) => c.featured);
}

export function getCountryBySlug(slug: string): CountryItem | undefined {
  return COUNTRIES_DATA.find((c) => c.slug.toLowerCase() === slug.toLowerCase());
}
