// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BotanicalLetterpressBusinessCard-L2B-Q6/App.tsx": () => import("../components/mockups/templates/BotanicalLetterpressBusinessCard-L2B-Q6/App.tsx"),
  "./components/mockups/templates/SwissGridCRMDashboard-MGqMAI/App.tsx": () => import("../components/mockups/templates/SwissGridCRMDashboard-MGqMAI/App.tsx")
};
